cmusphinx/pocketsphinx

swig/ps_decoder.i

It is essential in managing memory in other applications, else the Decoder keeps growing in size with each grammar added.

Expose unset_search via Swig.

---

swig/java/Makefile

The old Makefile for Java SWIG only worked on Linux. I have edited the Makefile so it can now produce libpocketsphinx_jni.dylib, which is what Java on MacOS is looking for.

Makefile for Java SWIG now also works on MacOS

---

src/libpocketsphinx/allphone_search.c

Running allphone_backtrace multiple times clears previously allocated segments, but no one ever clears the most recently allocated ones, creating a memory leak which Valgrind attributes to the most recent time allphone_backtrace was run. allphone_search_free seems like the obvious place to do clean it up.

Fix memory leak in allphone_search.c

---

src/libpocketsphinx/allphone_search.c

My previous commit broke compilation because the declaration order of the static functions is off (very sorry about that). Rather than moving functions around, it seemed more natural to put this forward declaration in in the same place as the existing one for allphone_backtrace.
Like I should have done last time, I've tested this and it compiles and seems to run correctly (passes the unit tests, doesn't leak).
Edit to add: this resolves #139.

Forward declare allphone_clear_segments in allphone_search.c

---

src/gst-plugin/gstpocketsphinx.c

The gstreamer element was missing the option to handle Java Speech Grammar Format (JSGF) files.

Support -jsgf switch in gstreamer

---

src/libpocketsphinx/acmod.h
src/libpocketsphinx/allphone_search.h
src/libpocketsphinx/bin_mdef.h
src/libpocketsphinx/blkarray_list.h
src/libpocketsphinx/dict.h
src/libpocketsphinx/dict2pid.h
src/libpocketsphinx/fsg_history.h
src/libpocketsphinx/fsg_lextree.h
src/libpocketsphinx/fsg_search_internal.h
src/libpocketsphinx/hmm.h
src/libpocketsphinx/kws_detections.h
src/libpocketsphinx/kws_search.h
src/libpocketsphinx/mdef.h
src/libpocketsphinx/ms_gauden.h
src/libpocketsphinx/ms_mgau.h
src/libpocketsphinx/ms_senone.h
src/libpocketsphinx/ngram_search.h
src/libpocketsphinx/ngram_search_fwdflat.h
src/libpocketsphinx/ngram_search_fwdtree.h
src/libpocketsphinx/phone_loop_search.h
src/libpocketsphinx/pocketsphinx_internal.h
src/libpocketsphinx/ps_alignment.h
src/libpocketsphinx/ps_lattice_internal.h
src/libpocketsphinx/ptm_mgau.h
src/libpocketsphinx/s2_semi_mgau.h
src/libpocketsphinx/s3types.h
src/libpocketsphinx/state_align_search.h
src/libpocketsphinx/tied_mgau_common.h
src/libpocketsphinx/tmat.h
src/libpocketsphinx/vector.h

This pull request makes the following changes:
- Most struct declarations were of the form `typedef struct name_s { /* data fields */ } name_t`, but some were typedef'd anonymously (without `name_s`): `typedef struct { /* data fields */ } name_t`. This made it impossible to forward declare them. I have added the `name_s` part to all headers which omitted it.
- A seemingly random selection of the internal headers had the `extern "C"` required for linking with C++, but many did not have it; also, most of the internal headers containing `extern "C"` used a style that differed from the style used in the public API headers, and some had extraneous semicolons which caused compiler warnings. I have added the directive to all internal headers and unified the style with that of the public API …

Improve linking for internal headers

---

src/libpocketsphinx/fsg_search.c

In the current trunk, all lattice-related code in `fsg_search.c` is unreachable. This was apparently done for performance reasons, but was not documented anywhere. This pull request adds a compiler flag to re-enable the code along with a few brief comments explaining why the code doesn't work by default.
Resolves issue #177.

Add macro to enable dead -bestpath code in fsg_search

---

configure.ac

PKG_PROG_PKG_CONFIG properly detects the cross-compilation pkg-config
when cross-compilation is requested.

Fix pkg-config use for cross-compilation

---

include/sphinxbase/bitarr.h
src/lm/lm_trie.c
src/lm/lm_trie.h
src/lm/lm_trie_quant.c
src/lm/lm_trie_quant.h
src/lm/ngram_model_trie.c
src/util/bitarr.c
test/unit/test_ngram/test_lm_read.c
test/unit/test_ngram/test_lm_write.c
test/unit/test_util/test_bitarr.c

All tests should now pass on S390, and, presumably, other big-endian machines.  Should notably fix https://github.com/cmusphinx/pocketsphinx/issues/252
I don't know who wrote the bitarr and lm_trie code but I would like a word with them.  It is undocumented and inscrutable and the fact that it is full of assumptions that make it break on other architectures doesn't give me confidence in its correctness or security.

Fix endianness issues in binary trie LM code

---

programs/CMakeLists.txt

Currently, when building for iOS or Mac (in my case, building for iOS, I have `CMAKE_SYSTEM_NAME = iOS` ), you'll get this error:
```
CMake Error at programs/CMakeLists.txt:16 (install):
install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
target "pocketsphinx_batch".
```
Reference to doc mentioned in comment: https://cmake.org/cmake/help/latest/prop_tgt/MACOSX_BUNDLE.html#prop_tgt:MACOSX_BUNDLE

Fix install command for Mac and iOS builds

---

cython/_pocketsphinx.pxd
cython/_pocketsphinx.pyx
cython/test/continuous_test.py
include/pocketsphinx.h
include/sphinxbase/cmn.h
src/acmod.c
src/feat/cmn.c
src/feat/cmn_live.c
src/pocketsphinx.c
test/unit/test_acmod.c
test/unit/test_ps.c

The hack with the "-cmninit" parameter really didn't work right, and also, it prevented us from doing cool (maybe useful) things like setting and getting the CMN in the middle of an utterance.

Add a proper API for cepstral mean normalization

---

include/pocketsphinx.h
src/acmod.c
src/acmod.h
src/allphone_search.c
src/allphone_search.h
src/bin_mdef.c
src/bin_mdef.h
src/dict.c
src/dict.h
src/fsg_search.c
src/fsg_search_internal.h
src/kws_search.c
src/kws_search.h
src/ms_gauden.c
src/ms_gauden.h
src/pocketsphinx.c
src/pocketsphinx_internal.h

For the moment we just rename cmd_ln_t and make a macro to simplify its use, but this will be improved.

Begin the cleanup of the configuration API

---

src/allphone_search.c
src/ms_gauden.c
src/ms_mgau.c
src/ms_senone.c
src/ngram_search_fwdtree.c
src/ps_lattice.c
src/ptm_mgau.c
src/s2_semi_mgau.c
src/tied_mgau_common.h
test/unit/test_ngram_model_read.c

IIRC float to integer conversion is somewhat underspecified in IEEE754, and MIPS and other architectures do different things, leading to unpredictable (and bad) decoding results.
In any case we shouldn't be underflowing in the first place!!
This should fix that everywhere, and also clarifies some magic constants to be less magic.

Fix float-to-int underflows (#199, #252)

---

cython/_pocketsphinx.pyx
cython/test/config_test.py
include/pocketsphinx.h
src/pocketsphinx.c
src/ps_config.c
test/unit/test_config.c

Python API does some helpful things to avoid surprises.

Disallow multiple search types in config or command-line

---

cython/test/config_test.py
cython/test/kws_test.py
src/kws_detections.c
src/kws_search.c
src/kws_search.h
test/data/goforward.kws
test/unit/test_keyphrase.c

While it's true that kws search is not necessarily intended to give you more than one detected keyword at a time, if you are using it to spot phrases in a pre-existing file, you might like to have them in the order they were spoken, rather than backwards.

Make seg_iter and hyp behave as expected in kws search (fixes #122)

---

include/pocketsphinx/model.h

Does not compile when included from .cpp file because of missing closing brace.

Add missing close brace for C++

---

pocketsphinx.pc.in

Assuming there was an attempt to use pthread, the current version of PocketSphinx does not rely on pthread.
Therefore, unnecessary libpthread has been removed from the pkg-config include file to avoid any misunderstanding.

Removed unnecessary libpthread in package config

---

README.md
pocketsphinx.pc.in

SphinxBase is still included in package config file.
Removed it.

Removed unnecessary shinxbase in package config

---

cython/test/alignment_test.py
src/state_align_search.c

While we explcitly disable `bestpath` in the command-line for phone and state alignment due to its tendency to put fake `</s>` with a duration of a single frame at the end of the utterance, this was not the case in the Python API, either because I forgot, but most likely for Reasons (some people apparently use `bestpath` with FSG search or alignment, don't ask me why).
This is a more robust fix, which will simply refuse to force-align something to an impossible duration.  We may also wish to fix the upstream problem of the fake `</s>` but that is more complex to do.  This at least prevents crashing!

Do not attempt to align phones to impossibly short durations (fixes #339)

---

.github/workflows/tests.yml
pyproject.toml

There is a very long saga in the `scikit-build` issues about this, which I haven't read, but did read enough to know that `setuptools>=64` breaks `pip install -e`.
So make sure to use `setuptools<64`.
See: https://github.com/scikit-build/scikit-build/issues/981

Require specific setuptools version to fix editable install (fixes: #353)

---

cython/_pocketsphinx.pyx

make the pocketsphinx.Decoder.set_alignment example print something legible

Fix _pocketsphinx.pyx's set_alignment example

---

src/lm/ngram_model.c
test/unit/CMakeLists.txt
test/unit/test_lm_convert.c
tox.ini

- Modified ngram_model_read() to check if 'lw' and 'wip' parameters exist before trying to read them using ps_config_typeof()
- These decoder-specific parameters are not required for language model conversion tools like pocketsphinx_lm_convert
- Added test_lm_convert to verify language models can be read without these parameters
- Fixes #399

Fix pocketsphinx_lm_convert failing due to missing lw/wip parameters

---

CMakeLists.txt
config.h.in
docs/thread_safety.md
src/util/genrand.c
src/util/genrand.h
src/util/thread_local.h
test/unit/CMakeLists.txt
test/unit/test_genrand_baseline.c
test/unit/test_genrand_thread.c
test/unit/test_genrand_thread_tls.c
test/unit/test_thread_local_basic.c
test/unit/test_thread_local_compile.c
test/unit/test_thread_utils.c
test/unit/test_thread_utils.h
test/unit/test_thread_utils_self.c
tox.ini

This PR makes the Mersenne Twister random number generator (RNG) in PocketSphinx thread-safe by using thread-local storage (TLS) for its state variables. This eliminates race conditions and data corruption when multiple threads use the RNG concurrently.
The RNG implementation used global static variables (`mt[]` array and `mti` index) that were shared across all threads, causing:
- Race conditions in multi-threaded applications
- Non-deterministic behavior
- Potential data corruption
- Thread safety issues in speech recognition pipelines
- Add platform-agnostic thread-local storage abstraction (`PS_THREAD_LOCAL` macro)
- Make RNG state variables thread-local, giving each thread its own independent RNG state
- Maintain complete backward compatibility - no API changes required
✅ **Fully …

Add thread-local random number generator for thread safety
